image: docker:latest
services:
    - docker:dind

stages: 
  - build
  - deploy

build:
  stage: build
  only:
    - master
  before_script:
    - apk add --no-cache py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
    - pip install docker-compose
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker-compose build
    - docker-compose push

# deploy-dev:
#   stage: deploy
#   only:
#     - develop
#   script:
#     - echo "deploy-dev success"

deploy-prod:
  stage: deploy
  only:
    - master
  before_script:
    - apk add --no-cache openssh openssh-client bash rsync
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - bash -c 'ssh-add <(echo "$DEPLOY_PRIVATE_KEY")'
  script:
    - rsync -rav --delete ./ deploy@$SERVER_ADDR:/usr/app/source/
    - ssh -p22 deploy@$SERVER_ADDR "/usr/app/source/deploy.bash -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD -r $CI_REGISTRY"