package conf

const (
	MYSQL_SERVER_ADDR = "127.0.0.1"
	MYSQL_LOGIN = "remoteRoot"
	MYSQL_PASSWORD = "=7n/4Z%"
	MYSQL_DB_MAIN = "forcamp"
	MYSQL_SERVER_PORT = ":3306"
	MYSQL_LOCAL_LOGIN = "root"
	MYSQL_LOCAL_PASSWORD = "=7n/4Z%"
	MYSQL_MAX_USER_CONNECTIONS = 151
)